name: Build & Deploy page

on:
  push:
    branches:
      - "2024"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Deploy page
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DEPLOY_PROJECT_NAME: resume
          DEPLOY_BRANCH: main
        run: |
          bun x wrangler pages deploy public \
          --project-name "${DEPLOY_PROJECT_NAME}" \
          --branch "${DEPLOY_BRANCH}" \
          --commit-dirty=true
